watch:
  - "templates/**/*.liquid"
  - "settings.yml"
  - "custom-fields.yml"

custom_fields:
  message: "Hello, World!"
  subtitle: "- Your TRMNL"
  font_style: "classic"
  border_style: "simple"
  text_align: "center"
  sign_theme: "standard"
  show_date: "yes"
  qr_url: ""
